# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('checker', '0002_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
