# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_task_default_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['price']},
        ),
    ]
