badip:
    build: ../../badip
    command: python3 server.py
nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /var/www/qctf-starter-2016/:/var/www
      - /var/www/qctf-starter-2016/deploy/simple-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - badip:ro
