version: '2'
services:
  mysql:
    image: mysql
    env_file: ./production.env
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  memcached:
    image: memcached
    ports:
      - "127.0.0.1:11211:11211"

  gallery:
    build: ./gallery
    depends_on:
      - mysql
      - memcached
    env_file: ./production.env
    volumes:
      - ./gallery/static/photos:/app/static/photos

  nginx:
    image: nginx
    depends_on:
      - gallery
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

