
    je     _correct_flag


_err_length:
    ; generated by python
    mov    dword [esp + 0], 0x6e6f7257
    mov    dword [esp + 4], 0x656c2067
    mov    dword [esp + 8], 0x7468676e
    mov    dword [esp + 12], 0x00000a21
    mov    eax, 0x4
    mov    ebx, 0x2
    mov    ecx, esp
    mov    edx, 14
    int    0x80
    jmp    _exit


_err_b64:
    ; generated by python
    mov    dword [esp + 0], 0x6e6f7257
    mov    dword [esp + 4], 0x6f662067
    mov    dword [esp + 8], 0x74616d72
    mov    dword [esp + 12], 0x00000a21
    mov    eax, 0x4
    mov    ebx, 0x2
    mov    ecx, esp
    mov    edx, 14
    int    0x80
    jmp    _exit


_correct_flag:
    ; generated by python
    mov    dword [esp + 0], 0x72726f43
    mov    dword [esp + 4], 0x21746365
    mov    dword [esp + 8], 0x0000000a
    mov    eax, 0x4
    mov    ebx, 0x2
    mov    ecx, esp
    mov    edx, 9
    int    0x80
    jmp    _exit


_incorrect_flag:
    ; generated by python
    mov    dword [esp + 0], 0x6f636e49
    mov    dword [esp + 4], 0x63657272
    mov    dword [esp + 8], 0x000a2174
    mov    eax, 0x4
    mov    ebx, 0x2
    mov    ecx, esp
    mov    edx, 11
    int    0x80
    jmp    _exit


_exit:
    ; exit
    mov    eax, 1    ; eax = sys_exit
    xor    ebx, ebx  ; ebx = exit code (0)
    int    0x80
