# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20161114_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='replace_info',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
