# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_team_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 22, 15, 1, 59, 382225, tzinfo=utc)),
        ),
    ]
