# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_auto_20161123_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
