# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_auto_20161125_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='tasks_number',
            field=models.IntegerField(default=0),
        ),
    ]
