CREATE DATABASE IF NOT EXISTS gallery;
USE gallery;
DROP TABLE Users;
DROP TABLE Photos;
CREATE TABLE Users (Id INTEGER PRIMARY KEY  AUTO_INCREMENT  NOT NULL  UNIQUE , Username VARCHAR(50) NOT NULL  UNIQUE , `Hash` CHAR(64) NOT NULL );
CREATE TABLE Photos (Id INTEGER PRIMARY KEY  AUTO_INCREMENT NOT NULL ,UserId INTEGER NOT NULL ,UploadTime DATETIME NOT NULL ,LatitudeRef VARCHAR(255) NOT NULL ,Latitude INTEGER NOT NULL ,LongitudeRef VARCHAR(255) NOT NULL ,Longitude INTEGER NOT NULL ,Filename VARCHAR(255) NOT NULL ,IsFeatured BOOL NOT NULL  );