# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminclar',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='userclar',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='adminclar',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclar',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
