# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_auto_20161123_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Test Team!', max_length=100),
            preserve_default=False,
        ),
    ]
