# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_auto_20161124_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
