# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_auto_20161125_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
