# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_team_last_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='last_submit',
        ),
        migrations.AddField(
            model_name='team',
            name='sumbit_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
