# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_team_stolen_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='sumbit_time',
            new_name='submit_time',
        ),
    ]
