# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0019_auto_20161126_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
