# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Hello world', max_length=64),
            preserve_default=False,
        ),
    ]
