# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_auto_20161114_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='name',
            field=models.CharField(default='Test value', max_length=100),
            preserve_default=False,
        ),
    ]
