# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20161114_1011'),
        ('checker', '0006_hint_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='hint',
            name='owners',
            field=models.ManyToManyField(related_name='hints', to='cabinet.Team'),
        ),
    ]
