# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0017_auto_20161125_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.Task'),
        ),
    ]
