# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0018_submit_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['price', 'title']},
        ),
    ]
