# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_team_replace_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 20, 9, 45, 41, 857380, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
