# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarifications', '0002_auto_20161125_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminclar',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='userclar',
            options={'ordering': ['-time']},
        ),
    ]
