# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_team_tasks_number'),
        ('checker', '0003_auto_20161106_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='task',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='team',
        ),
        migrations.AddField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(related_name='tasks', to='cabinet.Team'),
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
