# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_auto_20161114_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='hints', to='cabinet.Team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='cabinet.Team'),
        ),
    ]
