version: '2'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db

    mem_limit: 1250M

  elasticsearch:
    image: elasticsearch
    restart: always
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

    mem_limit: 1250M
    memswap_limit: 1250M

  auth:
    build: ./search-engine
    command: gunicorn search_engine.auth:app
    depends_on:
      - mongo
    env_file: ./production.env
    restart: always

  crawler:
    build: ./search-engine
    command: python3 -m search_engine.crawler
    depends_on:
      - mongo
      - elasticsearch
    env_file: ./production.env
    links:
      - auth:auth.local
    restart: always
    
  front:
    build: ./search-engine
    command: gunicorn search_engine.front:app
    depends_on:
      - elasticsearch
      - mongo
    env_file: ./production.env
    links:
      - auth:auth.local
    restart: always

  nginx:
    image: nginx
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
